### ISSUE TITLE
preprocessing problem

### ISSUE THREAD

**Issue by zzpustc** [zzh142857/SiameseFC-tf#2]
Hello! Have you process the training data to make the target locate in the center of image? And I have noticed that your loss is different from the original paper, you obtain it after a  resize_bilinear step, but in the original paper, the author obtain the loss from the last 17*17 feature map, can you explain the reason of your procedure? thx!

**Comment by zzh142857** [comment]
Hi. For the first question, yes. The previous description in README.md file is wrong. And I've fixed it. This is done during the cropping step in src/crops.py. For the second question, you are right. I calculate the loss after resizing the score map. I think both are OK, and I really don't know which one is better. My starting point is since we will use the resized score map to locate the target during tracking, so I just calculate the loss of this final score map.

**Comment by aaon22357** [comment]
Hello, I'm a newer in tensorflow, I have a question about two parameters,what does "resize_height=700" and "resize_width=700" mean in \parameters\design.json?Can I reduce these parameters? And when I run the code,I met an error '"OOM" when allocating tensor with shape[275338,275338,3] ', my device is GTX1080 and Intel Core i7-8700CPU,64GRAM, I don't know how to deal with this problem,can you help me? Thank you.

**Comment by zzh142857** [comment]
Hi @aaon22357, the size of the image in different videos are different, so I resize them to have a uniform width and height. You can definitely change its value and play with it. For the second problem, the error "00M" means you are out of memory. Are you using your graphic card to run this model or the CPU? For me, I use s GTX1070 to run the model and it works OK. Maybe you can try to reduce the value of batch_size or the size of reading queue(src/read_training_dataset.py line 76).

**Comment by aaon22357** [comment]
@zzh142857 Thank you so much, I have tried your suggests, I set the batch_size=2,min_after_dequeue = 10, but there are still several errors:
![2](https://user-images.githubusercontent.com/36906805/44626600-a5912c80-a951-11e8-8ff1-f8660910582e.png)
what's more, the tensor shape is different every time and varies a lot in the 'OOM' line. I can't understand what's wrong with it.

**Comment by zzh142857** [comment]
@aaon22357 I think this means something is wrong with your code or running environment. I just download this repository and train the model from scratch, and everything is fine. So first you can check if your graphic card is working properly: type `python`or`python3` in command line to enter Interactive Python Console, import tensorflow `import tensorflow as tf`, and start a session `tf.Session()`. Then it should print the information about your running environment. You can go through thoses logs and make sure your tensorflow is running on your graphic card, as well as there is enough memory on your card, below is the result I got from my laptop:
![image](https://user-images.githubusercontent.com/26756469/44632987-80e98480-a952-11e8-8b94-a5ad4361d1be.png)

you can see I'm using a grforce 820M graphic card, and there are 823.06MB free space left. In your case it should shows the information of your 1080 card, and the free space should be much larger.

If the running environment is fine, then there must be something wrong with your code. Have you tried to change any parameters? You can download the original code and run it again. And also, when you run the model(run_tracker_training.py), the console will first print out the structure of the network, like this:
![image](https://user-images.githubusercontent.com/26756469/44632954-d4a79e00-a951-11e8-92a2-99f2a5292205.png)
so you probably also want to check it to make sure there isn't any crazy numbers in your model.

Let me know if these still cannot fix your problem. Good luck~

**Comment by aaon22357** [comment]
@zzh142857 Thank you, I found the error at last, because I have use the VOT2015 dataset to train model, it has 8 coordinates for each boundingbox,while the OTB has only 4 coordinates, during generating the 'txt' files, I only ignored the assert len(z_gt)==4, but didn't change other codes, I think it may led to insufficient memory, when I used the OTB datasets, the problem was finally solved. Thank you again for your help.

**Comment by zzh142857** [comment]
@aaon22357 Glad to hear that~ Good luck~
