### ISSUE TITLE
Processing of labels

### ISSUE THREAD

**Issue by aaon22357** [zzh142857/SiameseFC-tf#3]
Hello, I come here again, I want to ask a few questions in /src/trainer.py .
Firstly, I don't know the meaning of  " x_sz = float(design.search_sz) / design.exemplar_sz * x_sz" mean?(src/trainer.py line 78),I think it may should be this "x_sz = float(design.search_sz) / design.exemplar_sz * z_sz".
Another question is,  why the labels can be calculated by the function named '_create_gt_label_final_score_sz'?  I found that the bounding box coordinates are resized by design.resize_width when preparing batched_data(/src/read_training_dataset.py),but when generate labels, you just use "label_w = int(x_target_w_[i] * search_sz / x_sz[i])"(trainer.py line 162),can this way convert to the original coordinates? Is it unnecessary to divide design.resize_width ? Hope for your answer,thank you.

**Comment by zzh142857** [comment]
Hi @aaon22357 , For the first question, x_sz is the cropping size of image x, and z_sz is the cropping size of z. The target has different scale in x and z, and we want to crop them separately to have a uniform scale and input to the conv network. So x_sz shouldn't be determined by z_sz. They don't have any relationship.
And for the label size, I actually resized all the training images to have a uniform size of resize_width*resize_height when making the tfrecords file. So I can just using the resized width and height to generate the groundtruth label. Let me know if you have any further questions. Best~

**Comment by aaon22357** [comment]
@zzh142857  Thank you so much,you solved my problem,grateful for your help
